### ISSUE TITLE
Windows 8 src install error

### ISSUE THREAD

**Issue by ghost** [autotelicum/Smooth-CoffeeScript#25]
What can i do for installing Smooth-Coffee-Script in Windows 8.....
I purchase your book. and I feel i'm lost in 5p. I want to go further.
Could you let me know how i can solve this error message??

I intslled npm v0.9.8 , because 0.6.6 you recommended can't install coffee script with global in windows 8.
then, I trying to install Smooth-Coffee-scripts src. but i'ts fail.

here's the error message :

---

D:\coffeescript\Smooth-CoffeeScript-master\src>coffee 01-Introduction.coffee
SyntaxError: In D:\coffeescript\Smooth-CoffeeScript-master\src\prelude\prelude.c
offee, octal escape sequences "\033[32m#{str}\033[0m" are not allowed on line 21
8
    at SyntaxError (<anonymous>)
    at Lexer.exports.Lexer.Lexer.error (C:\Users\사용자\AppData\Roaming\npm\node_m
odules\coffee-script\lib\coffee-script\lexer.js:682:13)
    at Lexer.exports.Lexer.Lexer.stringToken (C:\Users\사용자\AppData\Roaming\npm\
node_modules\coffee-script\lib\coffee-script\lexer.js:170:14)
    at Lexer.exports.Lexer.Lexer.tokenize (C:\Users\사용자\AppData\Roaming\npm\nod
e_modules\coffee-script\lib\coffee-script\lexer.js:33:137)
    at exports.compile.compile (C:\Users\영수\AppData\Roaming\npm\node_modules\c
offee-script\lib\coffee-script\coffee-script.js:47:32)
    at Object.require.extensions..coffee (C:\Users\사\AppData\Roaming\npm\node
_modules\coffee-script\lib\coffee-script\coffee-script.js:27:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
## D:\coffeescript\Smooth-CoffeeScript-master\src>

so, i install  the libraries manually.
1. underscore
   $npm --global install underscore
2. coffeekup
   $npm --global install coffeekup
3. node.ws.js
   $npm --global install ws
   $npm --global install websocket
   $npm --global install socket.io
4. qc.js  - google has no result for install qc.js for coffeescript. oh. headache...

**Comment by ghost** [comment]
during installation process.. 
there're conflicts among components with version.
1. using NVM install proper node.js
2. using NVM install coffee-scrpt master branch.
3. then.. use source of smooth-coffee-script. 

that's all.
